---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: "https://haveibeenpwned.com/api/v3/breaches\r\n\r\nhttps://usetrmnl.com/custom_plugin_example_data.json"
polling_headers: ''
polling_body: ''
id: 183668
custom_fields:
- keyname: about
  name: About This Plugin
  field_type: author_bio
  description: Keep up to date with the latest data breaches.
  github_url: https://github.com/ExcuseMi/trmnl-databreaches-plugin
  learn_more_url: https://haveibeenpwned.com
name: Data Breaches
refresh_interval: 15
